[package]
name = "whisper_realtime"
version = "0.1.0"
edition = "2021"
# TODO LICENSE, DESCRIPTION, DOCS, REPO

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.204", features = ["derive"], optional = true }
#whisper-rs = { version = "0.11.1", features = ["whisper-cpp-log", "whisper-cpp-tracing"] }

#  Version 12.1 - switch to cargo once crate is refreshed.
whisper-rs = { git = "https://github.com/tazz4843/whisper-rs.git", rev = "744804a", features = ["whisper-cpp-log", "whisper-cpp-tracing"] }
log = "0.4.21"
ctrlc = "3.4.4"
# voice_activity_detector builds without HW acceleration atm; looking into this.
voice_activity_detector = "0.1.0"
sdl2 = "0.37.0"
indicatif = "0.17.8"
reqwest = { version = "0.12.5", features = ["blocking", "stream"] }
futures = "0.3.30"
futures-util = "0.3.30"
futures-core = "0.3.30"
bytes = "1.6.1"
tokio = { version = "1.39.2", features = ["rt-multi-thread"] }
num-traits = "0.2.19"
lazy_static = "1.5.0"
realfft = "3.3.0"
hound = "3.5.1"

# See: https://github.com/tazz4843/whisper-rs/blob/master/BUILDING.md for building on Windows/MacOS
[target.aarch64-apple-darwin]
rustflags = "-lc++ -l framework=Accelerate"

[target.x86_64-pc-windows-gnu]
linker = "C:\\msys64\\ucrt64\\bin\\gcc.exe"
ar = "C:\\msys64\\ucrt64\\bin\\ar.exe"

[features]
default = []
_gpu = []
serde = ["dep:serde"]
cuda = ["whisper-rs/cuda", "_gpu"]
# openblas is Windows only, cpu acceleration.
openblas = ["whisper-rs/openblas"]
# Linux only
# ROCm support for AMD GPUs - Linux only
hipblas = ["whisper-rs/hipblas", "_gpu"]
coreml = ["whisper-rs/coreml"]
metal = ["whisper-rs/metal", "_gpu"]
# If OpenCL is enabled, GPU is always enabled.
# It is not feasible to use it with large models for realtime
opencl = ["whisper-rs/opencl"]




