[package]
name = "whisper_realtime_gui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bson = "2.11.0"
cpal = "0.15.3"
directories = "5.0.1"
packer = "0.5"
serde = { version = "1.0.203", features = ["derive"] }
tokio = "1.38.0"
ureq = "2.9.7"
whisper-rs = { version = "0.11.1", features = ["whisper-cpp-log", "whisper-cpp-tracing"] }
log = "0.4.21"
egui = "0.27.2"
bbqueue-sync = "0.5.1"
ctrlc = "3.4.4"

[target.aarch64-apple-darwin]
rustflags = "-lc++ -l framework=Accelerate"

[features]
default = []
cuda = ["whisper-rs/cuda"]
coreml = ["whisper-rs/coreml"]
opencl = ["whisper-rs/opencl"]


