[package]
name = "whisper_realtime"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bson = "2.11.0"
directories = "5.0.1"
serde = { version = "1.0.204", features = ["derive"] }
ureq = "2.9.7"
whisper-rs = { version = "0.11.1", features = ["whisper-cpp-log", "whisper-cpp-tracing"] }
log = "0.4.21"
ctrlc = "3.4.4"
voice_activity_detector = "0.1.0"
sdl2 = "0.37.0"

[target.aarch64-apple-darwin]
rustflags = "-lc++ -l framework=Accelerate"


[features]
default = []
cuda = ["whisper-rs/cuda"]
coreml = ["whisper-rs/coreml"]
opencl = ["whisper-rs/opencl"]


