[package]
name = "whisper_realtime"
version = "0.1.0"
edition = "2021"
# TODO LICENSE, DESCRIPTION, DOCS, REPO

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.204", features = ["derive"], optional = true }
# TODO: swap to reqwest
ureq = "2.9.7"
whisper-rs = { version = "0.11.1", features = ["whisper-cpp-log", "whisper-cpp-tracing"] }
log = "0.4.21"
ctrlc = "3.4.4"
voice_activity_detector = "0.1.0"
sdl2 = "0.37.0"
indicatif = "0.17.8"
reqwest = { version = "0.12.5", features = ["blocking", "stream"] }
futures = "0.3.30"
futures-util = "0.3.30"
futures-core = "0.3.30"
bytes = "1.6.1"

# Cmake is required. Download with homebrew or from cmake.org and add to $PATH.
[target.aarch64-apple-darwin]
rustflags = "-lc++ -l framework=Accelerate"

[target.x86_64-pc-windows-gnu]
linker = "C:\\msys64\\ucrt64\\bin\\gcc.exe"
ar = "C:\\msys64\\ucrt64\\bin\\ar.exe"

# See: https://github.com/tazz4843/whisper-rs/blob/master/BUILDING.md for building on windows
# using MSVSC++

[features]
default = []
_gpu = []
use_serde = ["serde"]
cuda = ["whisper-rs/cuda", "_gpu"]
# openblas is Windows only, cpu acceleration.
openblas = ["whisper-rs/openblas"]
# Linux only - Not yet available in 0.11.1
# ROCm support for AMD GPUs.
# hipblas = ["whisper-rs/hipblas", "_gpu"]
coreml = ["whisper-rs/coreml"]
metal = ["whisper-rs/metal", "_gpu"]
opencl = ["whisper-rs/opencl"]




